// Swaranidhi Comprehensive Registry of Indian Languages (Eighth Schedule of the Constitution + English)
// Transparent capabilities: No fake speech recognition claimed.

export const INDIAN_LANGUAGES = [
  {
    code: 'en-IN',
    shortCode: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    region: 'Pan-India',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'Speak in English',
    sampleCommand: 'Add 20 packets of Maggi to stock',
    confirmText: 'Yes, Add',
    cancelText: 'Cancel',
  },
  {
    code: 'te-IN',
    shortCode: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu',
    region: 'South',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'తెలుగులో మాట్లాడండి',
    sampleCommand: 'మ్యాగీ 20 ప్యాకెట్లు స్టాక్లో యాడ్ చేయి',
    confirmText: 'అవును, యాడ్ చేయి',
    cancelText: 'రద్దు చేయి',
  },
  {
    code: 'hi-IN',
    shortCode: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    region: 'North / Central',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'हिंदी में बोलें',
    sampleCommand: 'मैगी के 20 पैकेट स्टॉक में जोड़ो',
    confirmText: 'हाँ, जोड़ें',
    cancelText: 'रद्द करें',
  },
  {
    code: 'ta-IN',
    shortCode: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    region: 'South',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'தமிழில் பேசுங்கள்',
    sampleCommand: '20 மேகி பாக்கெட்டுகளை ஸ்டாக்கில் சேர்க்கவும்',
    confirmText: 'ஆம், சேர்',
    cancelText: 'ரத்து செய்',
  },
  {
    code: 'kn-IN',
    shortCode: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada',
    region: 'South',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ',
    sampleCommand: 'ಮ್ಯಾಗಿ 20 ಪ್ಯಾಕೆಟ್ ಸ್ಟಾಕ್ಗೆ ಸೇರಿಸಿ',
    confirmText: 'ಹೌದು, ಸೇರಿಸಿ',
    cancelText: 'ರದ್ದುಮಾಡಿ',
  },
  {
    code: 'ml-IN',
    shortCode: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam',
    region: 'South',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'മലയാളത്തിൽ സംസാരിക്കൂ',
    sampleCommand: '20 പാക്കറ്റ് മാഗി സ്റ്റോക്കിൽ ചേർക്കൂ',
    confirmText: 'അതെ, ചേർക്കുക',
    cancelText: 'റദ്ദാക്കുക',
  },
  {
    code: 'mr-IN',
    shortCode: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari',
    region: 'West',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'मराठीत बोला',
    sampleCommand: 'मॅगीचे २० पॅकेट स्टॉकमध्ये जोडा',
    confirmText: 'होय, जोडा',
    cancelText: 'रद्द करा',
  },
  {
    code: 'bn-IN',
    shortCode: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali',
    region: 'East',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'বাংলায় বলুন',
    sampleCommand: 'ম্যাগির ২০টা প্যাকেট স্টকে যোগ করো',
    confirmText: 'হ্যাঁ, যোগ করুন',
    cancelText: 'বাতিল',
  },
  {
    code: 'gu-IN',
    shortCode: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati',
    region: 'West',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ગુજરાતીમાં બોલો',
    sampleCommand: 'મેગીના 20 પેકેટ સ્ટોકમાં ઉમેરો',
    confirmText: 'હા, ઉમેરો',
    cancelText: 'રદ કરો',
  },
  {
    code: 'pa-IN',
    shortCode: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    region: 'North',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲੋ',
    sampleCommand: 'ਮੈਗੀ ਦੇ 20 ਪੈਕਟ ਸਟਾਕ ਵਿੱਚ ਪਾ ਦਿਓ',
    confirmText: 'ਹਾਂ, ਸ਼ਾਮਲ ਕਰੋ',
    cancelText: 'ਰੱਦ ਕਰੋ',
  },
  {
    code: 'ur-IN',
    shortCode: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'Perso-Arabic',
    region: 'Pan-India',
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'اردو میں بولیں',
    sampleCommand: 'میگی کے 20 پیکٹ اسٹاک میں شامل کریں',
    confirmText: 'ہاں، شامل کریں',
    cancelText: 'منسوخ کریں',
  },
  {
    code: 'or-IN',
    shortCode: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    script: 'Odia',
    region: 'East',
    speechSupported: true,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ଓଡ଼ିଆରେ କୁହନ୍ତୁ',
    sampleCommand: 'ମ୍ୟାଗିର 20 ପ୍ୟାକେଟ୍ ଷ୍ଟକ୍ରେ ଯୋଡନ୍ତୁ',
    confirmText: 'ହଁ, ଯୋଡନ୍ତୁ',
    cancelText: 'ବାତିଲ କରନ୍ତୁ',
  },
  {
    code: 'as-IN',
    shortCode: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    script: 'Bengali-Assamese',
    region: 'North-East',
    speechSupported: true,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'অসমীয়াত কওক',
    sampleCommand: 'মেগীৰ ২০টা পেকেট ষ্টকত যোগ কৰক',
    confirmText: 'হয়, যোগ কৰক',
    cancelText: 'বাতিল কৰক',
  },
  {
    code: 'ne-IN',
    shortCode: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    script: 'Devanagari',
    region: 'North / East',
    speechSupported: true,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'नेपालीमा बोल्नुहोस्',
    sampleCommand: 'म्यागीको २० प्याकेट स्टकमा थप्नुहोस्',
    confirmText: 'हो, थप्नुहोस्',
    cancelText: 'रद्द गर्नुहोस्',
  },
  {
    code: 'kok-IN',
    shortCode: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    script: 'Devanagari',
    region: 'West',
    speechSupported: true,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'कोंकणींत उलययात',
    sampleCommand: 'मॅगीचे २० पाकिटां स्टॉकांत जोडा',
    confirmText: 'हय, जोडा',
    cancelText: 'रद्द करा',
  },
  {
    code: 'ks-IN',
    shortCode: 'ks',
    name: 'Kashmiri',
    nativeName: 'کٲشُر / कश्मीरी',
    script: 'Perso-Arabic / Devanagari',
    region: 'North',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'کٲشُر کلام',
    sampleCommand: 'میگی ہند 20 پیکٹ سٹاکس منز تھاوِو',
    confirmText: 'آں، تھاوِو',
    cancelText: 'منسوخ',
  },
  {
    code: 'sd-IN',
    shortCode: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي / सिन्धी',
    script: 'Arabic / Devanagari',
    region: 'West',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'سنڌيءَ ۾ ڳالهايو',
    sampleCommand: 'ميگي جا 20 پيڪيٽ اسٽاڪ ۾ شامل ڪريو',
    confirmText: 'ها، شامل ڪريو',
    cancelText: 'منسوخ',
  },
  {
    code: 'sa-IN',
    shortCode: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    script: 'Devanagari',
    region: 'Pan-India',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'संस्कृतेन वदतु',
    sampleCommand: 'मॅगी विंशति पुटकम् संचये योजयतु',
    confirmText: 'आम्, योजयतु',
    cancelText: 'निरस्यतु',
  },
  {
    code: 'mai-IN',
    shortCode: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    script: 'Devanagari',
    region: 'East',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'मैथिली मे बाजू',
    sampleCommand: 'मैगी के 20 पैकेट स्टॉक में जोड़ू',
    confirmText: 'हाँ, जोड़ू',
    cancelText: 'रद्द करू',
  },
  {
    code: 'doi-IN',
    shortCode: 'doi',
    name: 'Dogri',
    nativeName: 'डोगरी',
    script: 'Devanagari',
    region: 'North',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'डोगरी च गल्ल करो',
    sampleCommand: 'मैगी दे 20 पैकेट स्टाक च पा',
    confirmText: 'आहो, पाओ',
    cancelText: 'रद्द करो',
  },
  {
    code: 'brx-IN',
    shortCode: 'brx',
    name: 'Bodo',
    nativeName: 'बड़ो',
    script: 'Devanagari',
    region: 'North-East',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'बड़ो रायज्लाय',
    sampleCommand: 'मेगिनी 20 पेकेट स्टकाव दाजाब',
    confirmText: 'नंगौ, दाजाब',
    cancelText: 'नेवसि',
  },
  {
    code: 'mni-IN',
    shortCode: 'mni',
    name: 'Manipuri',
    nativeName: 'মৈতৈলোন্',
    script: 'Bengali / Meitei Mayek',
    region: 'North-East',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'মৈতৈলোন্দা ৱা ঙাংবিয়ু',
    sampleCommand: 'মেগী পেকেট ২০ স্তোক্তা হাপচিল্লু',
    confirmText: 'হোই, হাপচিল্লু',
    cancelText: 'লেপহন্নবা',
  },
  {
    code: 'sat-IN',
    shortCode: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    script: 'Ol Chiki / Devanagari',
    region: 'East',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ᱥᱟᱱᱛᱟᱲᱤᱛᱮ ᱨᱚᱲ ᱢᱮ',
    sampleCommand: 'ᱢᱮᱜᱤ ᱒᱐ ᱯᱮᱠᱮᱴ ᱤᱥᱴᱚᱠ ᱨᱮ ᱡᱩᱲᱟᱹᱭ ᱢᱮ',
    confirmText: 'ᱦᱮᱸ, ᱡᱩᱲᱟᱹᱭ ᱢᱮ',
    cancelText: 'ᱵᱟᱹᱜᱤ ᱢᱮ',
  },
  // Extended Regional Languages (Section 2)
  {
    code: 'bho-IN',
    shortCode: 'bho',
    name: 'Bhojpuri',
    nativeName: 'भोजपुरी',
    script: 'Devanagari',
    region: 'North / East',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'COMING_SOON',
    sampleVoiceHint: 'भोजपुरी में बोलीं',
    sampleCommand: 'मैगी के 20 पैकेट स्टॉक में डालब',
    confirmText: 'हाँ, डालीं',
    cancelText: 'रद्द करीं',
  },
  {
    code: 'raj-IN',
    shortCode: 'raj',
    name: 'Rajasthani',
    nativeName: 'राजस्थानी',
    script: 'Devanagari',
    region: 'West',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'COMING_SOON',
    sampleVoiceHint: 'राजस्थानी में बोलो',
    sampleCommand: 'मैगी रा 20 पैकेट स्टॉक में जोड़ो',
    confirmText: 'हाँ, जोड़ो',
    cancelText: 'रद्द करो',
  },
  {
    code: 'tcy-IN',
    shortCode: 'tcy',
    name: 'Tulu',
    nativeName: 'ತುಳು',
    script: 'Kannada',
    region: 'South',
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'COMING_SOON',
    sampleVoiceHint: 'ತುಳುಟು ಪಾತೆರ್ಲೆ',
    sampleCommand: 'ಮ್ಯಾಗಿ 20 ಪ್ಯಾಕೆಟ್ ಸ್ಟಾಕ್ಗ್ ಪಾಲೆ',
    confirmText: 'ಅಂದ್, ಪಾಲೆ',
    cancelText: 'ರದ್ದು ಮಲ್ಪುಲೆ',
  },
];

export const getLanguageByCode = (code = 'en-IN') => {
  if (!code) return INDIAN_LANGUAGES[0];
  const target = code.toLowerCase();
  return (
    INDIAN_LANGUAGES.find(
      (l) => l.code.toLowerCase() === target || l.shortCode.toLowerCase() === target
    ) || INDIAN_LANGUAGES[0]
  );
};

export const getSupportedIndianLanguages = () => INDIAN_LANGUAGES;

export default INDIAN_LANGUAGES;
