// =============================================================================
// Swaranidhi Central Language Configuration (Single Source of Truth)
// =============================================================================
// Defines all 22 Eighth Schedule Indian Languages + English with exact BCP-47 locales,
// native names, scripts, regions, and honest provider capabilities.
// =============================================================================

export const INDIAN_LANGUAGES = [
  {
    code: 'en',
    locale: 'en-IN',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    region: 'Pan-India',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'Speak in English',
    sampleCommand: 'Add 20 packets of Maggi',
    confirmText: 'Yes, Add',
    cancelText: 'Cancel',
  },
  {
    code: 'te',
    locale: 'te-IN',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu',
    region: 'South',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'తెలుగులో మాట్లాడండి',
    sampleCommand: 'మ్యాగీ 20 ప్యాకెట్లు జోడించండి',
    confirmText: 'అవును, జోడించు',
    cancelText: 'రద్దు చేయి',
  },
  {
    code: 'hi',
    locale: 'hi-IN',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    region: 'North / Central',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'हिंदी में बोलें',
    sampleCommand: 'मैगी के 20 पैकेट जोड़ो',
    confirmText: 'हाँ, जोड़ें',
    cancelText: 'रद्द करें',
  },
  {
    code: 'ta',
    locale: 'ta-IN',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    region: 'South',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'தமிழில் பேசுங்கள்',
    sampleCommand: 'மகி 20 பாக்கெட்டுகளைச் சேர்க்கவும்',
    confirmText: 'ஆம், சேர்',
    cancelText: 'ரத்து செய்',
  },
  {
    code: 'kn',
    locale: 'kn-IN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada',
    region: 'South',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ',
    sampleCommand: '20 ಮ್ಯಾಗಿ ಪ್ಯಾಕೆಟ್ಗಳನ್ನು ಸೇರಿಸಿ',
    confirmText: 'ಹೌದು, ಸೇರಿಸಿ',
    cancelText: 'ರದ್ದುಮಾಡಿ',
  },
  {
    code: 'ml',
    locale: 'ml-IN',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam',
    region: 'South',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'മലയാളത്തിൽ സംസാരിക്കൂ',
    sampleCommand: '20 മാഗി പാക്കറ്റുകൾ ചേർക്കുക',
    confirmText: 'അതെ, ചേർക്കുക',
    cancelText: 'റദ്ദാക്കുക',
  },
  {
    code: 'mr',
    locale: 'mr-IN',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari',
    region: 'West',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'मराठीत बोला',
    sampleCommand: 'मॅगीचे 20 पॅकेट जोडा',
    confirmText: 'हो, जोडा',
    cancelText: 'रद्द करा',
  },
  {
    code: 'bn',
    locale: 'bn-IN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali',
    region: 'East',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'বাংলায় বলুন',
    sampleCommand: '20 প্যাকেট ম্যাগি যোগ করুন',
    confirmText: 'হ্যাঁ, যোগ করুন',
    cancelText: 'বাতিল করুন',
  },
  {
    code: 'gu',
    locale: 'gu-IN',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati',
    region: 'West',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ગુજરાતીમાં બોલો',
    sampleCommand: '20 પેકેટ મેગી ઉમેરો',
    confirmText: 'હા, ઉમેરો',
    cancelText: 'રદ કરો',
  },
  {
    code: 'pa',
    locale: 'pa-IN',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    region: 'North',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲੋ',
    sampleCommand: 'ਮੈਗੀ ਦੇ 20 ਪੈਕਟ ਜੋੜੋ',
    confirmText: 'ਹਾਂ, ਜੋੜੋ',
    cancelText: 'ਰੱਦ ਕਰੋ',
  },
  {
    code: 'ur',
    locale: 'ur-IN',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'Perso-Arabic',
    region: 'Pan-India',
    browserSpeechSupported: true,
    speechSupported: true,
    textSupported: true,
    ttsSupported: true,
    status: 'SUPPORTED',
    sampleVoiceHint: 'اردو میں بولیں',
    sampleCommand: 'میگی کے 20 پیکٹ شامل کریں',
    confirmText: 'ہاں، شامل کریں',
    cancelText: 'منسوخ کریں',
  },
  {
    code: 'or',
    locale: 'or-IN',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    script: 'Odia',
    region: 'East',
    browserSpeechSupported: false,
    speechSupported: false, // Enabled via Cloud Speech (Bhashini/Whisper)
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'ଓଡ଼ିଆରେ କୁହନ୍ତୁ',
    sampleCommand: 'ମ୍ୟାଗିର 20 ପ୍ୟାକେଟ୍ ଯୋଡନ୍ତୁ',
    confirmText: 'ହଁ, ଯୋଡ଼ନ୍ତୁ',
    cancelText: 'ବାତିଲ କରନ୍ତୁ',
  },
  {
    code: 'as',
    locale: 'as-IN',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    script: 'Bengali-Assamese',
    region: 'North-East',
    browserSpeechSupported: false,
    speechSupported: false, // Enabled via Cloud Speech (Bhashini/Whisper)
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'অসমীয়াত কওক',
    sampleCommand: 'মেগীৰ ২০টা পেকেট ষ্টকত যোগ কৰক',
    confirmText: 'হয়, যোগ কৰক',
    cancelText: 'বাতিল কৰক',
  },
  {
    code: 'ne',
    locale: 'ne-NP',
    name: 'Nepali',
    nativeName: 'नेपाली',
    script: 'Devanagari',
    region: 'North / East',
    browserSpeechSupported: false,
    speechSupported: false, // Enabled via Cloud Speech (Whisper/Bhashini)
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'नेपालीमा बोल्नुहोस्',
    sampleCommand: 'म्यागीको २० प्याकेट स्टकमा थप्नुहोस्',
    confirmText: 'हुन्छ, थप्नुहोस्',
    cancelText: 'रद्द गर्नुहोस्',
  },
  {
    code: 'kok',
    locale: 'kok-IN',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    script: 'Devanagari',
    region: 'West',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'कोंकणींत उलययात',
    sampleCommand: 'मॅगीचे २० पाकिटां स्टॉकांत जोडा',
    confirmText: 'हय, जोडा',
    cancelText: 'रद्द करात',
  },
  {
    code: 'ks',
    locale: 'ks-IN',
    name: 'Kashmiri',
    nativeName: 'کٲشُر / कश्मीरी',
    script: 'Perso-Arabic / Devanagari',
    region: 'North',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'کٲشُر بولِو',
    sampleCommand: 'میگی ہند 20 پیکٹ سٹاکس منز تھاوِو',
    confirmText: 'آ، تھاوِو',
    cancelText: 'منسوخ کٔرِو',
  },
  {
    code: 'sd',
    locale: 'sd-IN',
    name: 'Sindhi',
    nativeName: 'سنڌي / सिन्धी',
    script: 'Arabic / Devanagari',
    region: 'West',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'سنڌيءَ ۾ ڳالھايو',
    sampleCommand: 'ميگي جا 20 پيڪيٽ اسٽاڪ ۾ شامل ڪريو',
    confirmText: 'ها، شامل ڪريو',
    cancelText: 'رد ڪريو',
  },
  {
    code: 'sa',
    locale: 'sa-IN',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    script: 'Devanagari',
    region: 'Pan-India',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'संस्कृतेन वदतु',
    sampleCommand: 'मॅगी विंशति पुटकम् संचये योजयतु',
    confirmText: 'आम्, योजयतु',
    cancelText: 'निरस्यतु',
  },
  {
    code: 'mai',
    locale: 'mai-IN',
    name: 'Maithili',
    nativeName: 'मैथिली',
    script: 'Devanagari',
    region: 'East',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'मैथिली में बाजू',
    sampleCommand: 'मैगी के 20 पैकेट स्टॉक में जोड़ू',
    confirmText: 'हाँ, जोड़ू',
    cancelText: 'रद्द करू',
  },
  {
    code: 'doi',
    locale: 'doi-IN',
    name: 'Dogri',
    nativeName: 'डोगरी',
    script: 'Devanagari',
    region: 'North',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'डोगरी च बोलो',
    sampleCommand: 'मैगी दे 20 पैकेट स्टाक च पाओ',
    confirmText: 'हाँ, पाओ',
    cancelText: 'रद्द करो',
  },
  {
    code: 'brx',
    locale: 'brx-IN',
    name: 'Bodo',
    nativeName: 'बड़ो',
    script: 'Devanagari',
    region: 'North-East',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'बड़ो रायलाय',
    sampleCommand: 'मेगीनि 20 पाकेट स्टकाव दाजाब',
    confirmText: 'औ, दाजाब',
    cancelText: 'गार',
  },
  {
    code: 'mni',
    locale: 'mni-IN',
    name: 'Manipuri',
    nativeName: 'মৈতৈলোন্ / Manipuri',
    script: 'Meitei Mayek / Bengali',
    region: 'North-East',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'মৈতৈলোন্দা ঙাংবীয়ু',
    sampleCommand: 'মেগী ২০ পেকেট স্তোক্তা হাপচিল্লু',
    confirmText: 'হোই, হাপচিল্লু',
    cancelText: 'লেপহন্নু',
  },
  {
    code: 'sat',
    locale: 'sat-IN',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    script: 'Ol Chiki',
    region: 'East',
    browserSpeechSupported: false,
    speechSupported: false,
    textSupported: true,
    ttsSupported: false,
    status: 'CLOUD_READY',
    sampleVoiceHint: 'ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ ᱨᱚੜ ᱢᱮ',
    sampleCommand: 'ᱢᱮᱜᱤ ᱒᱐ ᱯᱮᱠᱮᱴ ᱤᱥᱴᱚᱠ ᱨᱮ ᱡᱩᱲᱟᱹᱭ ᱢᱮ',
    confirmText: 'ᱦᱮᱸ, ᱡᱩᱲᱟᱹᱭ ᱢᱮ',
    cancelText: 'ᱵᱟᱹᱛᱤᱞ ᱢᱮ',
  },
];

/**
 * Lookup language by ISO code (e.g. 'ta') or BCP-47 locale (e.g. 'ta-IN')
 */
export const getLanguageByCodeOrLocale = (input = 'en-IN') => {
  if (!input) return INDIAN_LANGUAGES[0];
  const target = input.toLowerCase().trim();
  return (
    INDIAN_LANGUAGES.find(
      (l) =>
        l.code.toLowerCase() === target ||
        l.locale.toLowerCase() === target ||
        target.startsWith(l.code.toLowerCase() + '-') ||
        target.startsWith(l.locale.toLowerCase())
    ) || INDIAN_LANGUAGES[0]
  );
};

export const getLanguageLocale = (codeOrLocale) => {
  const lang = getLanguageByCodeOrLocale(codeOrLocale);
  return lang ? lang.locale : 'en-IN';
};

export const getLanguageCode = (codeOrLocale) => {
  const lang = getLanguageByCodeOrLocale(codeOrLocale);
  return lang ? lang.code : 'en';
};

export default INDIAN_LANGUAGES;
